"""AI Content Generator DB models — content storage, templates, packages.

All tables share Base from models.py so a single create_all() covers everything.
Each entity is independent — JSON blobs store variable-length lists/dicts.
"""

from __future__ import annotations

from datetime import datetime, timezone

from sqlalchemy import Boolean, DateTime, Index, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from telegram_bot.db.models import Base


def _now() -> datetime:
    return datetime.now(timezone.utc)


# ── GeneratedContent ──────────────────────────────────────────────


class GeneratedContent(Base):
    """Every piece of content generated by any AI Generator tool."""

    __tablename__ = "ag_content"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    gen_type: Mapped[str] = mapped_column(String(30))    # script|title|desc|tags|hashtags|...
    sub_type: Mapped[str] = mapped_column(String(50), default="default")  # shorts|funny|seo|...
    topic: Mapped[str] = mapped_column(String(300))
    content: Mapped[str] = mapped_column(Text)
    is_saved: Mapped[bool] = mapped_column(Boolean, default=False)
    project_id: Mapped[int | None] = mapped_column(Integer, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=_now)

    __table_args__ = (
        Index("ix_ag_type", "gen_type"),
        Index("ix_ag_saved", "is_saved"),
        Index("ix_ag_created", "created_at"),
    )


# ── AITemplate ────────────────────────────────────────────────────


class AITemplate(Base):
    """User-saved reusable template for any generator type."""

    __tablename__ = "ag_templates"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    template_type: Mapped[str] = mapped_column(String(30))   # script|title|desc|...
    name: Mapped[str] = mapped_column(String(200))
    category: Mapped[str] = mapped_column(String(50), default="general")
    content: Mapped[str] = mapped_column(Text)
    variables: Mapped[str] = mapped_column(Text, default="[]")  # JSON list of placeholder names
    usage_count: Mapped[int] = mapped_column(Integer, default=0)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=_now)

    __table_args__ = (
        Index("ix_tmpl_type", "template_type"),
        Index("ix_tmpl_cat", "category"),
        Index("ix_tmpl_active", "is_active"),
    )


# ── ContentPackage ────────────────────────────────────────────────


class ContentPackage(Base):
    """Full Video Package — all generators combined into one project bundle."""

    __tablename__ = "ag_packages"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    topic: Mapped[str] = mapped_column(String(300))
    character: Mapped[str] = mapped_column(String(200), default="")
    category: Mapped[str] = mapped_column(String(50), default="general")

    # Generated fields
    title: Mapped[str] = mapped_column(Text, default="")
    description: Mapped[str] = mapped_column(Text, default="")
    tags: Mapped[str] = mapped_column(Text, default="[]")              # JSON list
    hashtags: Mapped[str] = mapped_column(Text, default="[]")          # JSON list
    script: Mapped[str] = mapped_column(Text, default="")
    thumbnail_prompt: Mapped[str] = mapped_column(Text, default="")
    image_prompt: Mapped[str] = mapped_column(Text, default="")
    video_prompt: Mapped[str] = mapped_column(Text, default="")
    animation_prompt: Mapped[str] = mapped_column(Text, default="")
    voice_prompt: Mapped[str] = mapped_column(Text, default="")
    music_suggestions: Mapped[str] = mapped_column(Text, default="[]") # JSON list
    seo_summary: Mapped[str] = mapped_column(Text, default="")

    project_id: Mapped[int | None] = mapped_column(Integer, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=_now)

    __table_args__ = (
        Index("ix_pkg_topic", "topic"),
        Index("ix_pkg_created", "created_at"),
    )
